name : Website Deployment

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:

    runs-on : ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name : Checkout
      uses: actions/checkout@v1
    - run : npm install
    - run : npm run build
    - run : npm test

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-s3-bucket : ${{secrets.AWS_S3_BUCKET}}
        aws-access-key-id : ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: 'us-east-1'
        source_dir: 'build'

    - name: Deploy static site to S3 bucket
      run: aws s3 sync . s3://skill2skills-website --delete
      
